Traceback (most recent call last):
  File "/home/xavi/Documentos/PythonProjects/RepasoUnam/MyDevEnv/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/xavi/Documentos/PythonProjects/RepasoUnam/MyDevEnv/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/xavi/Documentos/PythonProjects/RepasoUnam/MyDevEnv/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/xavi/Documentos/PythonProjects/RepasoUnam/MyDevEnv/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/xavi/Documentos/PythonProjects/RepasoUnam/MyDevEnv/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/xavi/Documentos/PythonProjects/RepasoUnam/MyDevEnv/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/xavi/Documentos/PythonProjects/RepasoUnam/MyDevEnv/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import time
import matplotlib.pyplot as plt
from numpy.lib.stride_tricks import as_strided
plt.style.use('ggplot')
plt.rcParams.update({'font.size': 16, 'figure.figsize': (8,6), 'axes.grid': False})
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-30-05382af63e56>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0mtime[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0;32mimport[0m [0mmatplotlib[0m[0;34m.[0m[0mpyplot[0m [0;32mas[0m [0mplt[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0;32mfrom[0m [0mnumpy[0m[0;34m.[0m[0mlib[0m[0;34m.[0m[0mstride_tricks[0m [0;32mimport[0m [0mas_strided[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mplt[0m[0;34m.[0m[0mstyle[0m[0;34m.[0m[0muse[0m[0;34m([0m[0;34m'ggplot'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mplt[0m[0;34m.[0m[0mrcParams[0m[0;34m.[0m[0mupdate[0m[0;34m([0m[0;34m{[0m[0;34m'font.size'[0m[0;34m:[0m [0;36m16[0m[0;34m,[0m [0;34m'figure.figsize'[0m[0;34m:[0m [0;34m([0m[0;36m8[0m[0;34m,[0m[0;36m6[0m[0;34m)[0m[0;34m,[0m [0;34m'axes.grid'[0m[0;34m:[0m [0;32mFalse[0m[0;34m}[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'matplotlib'
ModuleNotFoundError: No module named 'matplotlib'

